version: 2.1

orbs: 
  sonarcloud: sonarsource/sonarcloud@2.0.0
  snyk: snyk/snyk@1.5.0

executors:
  android-executor:
    docker:
      - image: cimg/android:2025.04 
    working_directory: ~/library-app
    environment:
      GRADLE_OPTS: -Xmx3200m -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx3200m

commands:
  fix-gradlew:
    steps:
      - run: sed -i 's/\r$//' gradlew && chmod +x gradlew

  restore-gradle-cache:
    steps:
      - restore_cache:
          keys:
            - v1-gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-

  save-gradle-cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-gradle-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Crear local.properties
          command: echo "sdk.dir=/opt/android/sdk" > local.properties
      - fix-gradlew
      - restore-gradle-cache
      
      - save-gradle-cache
      - store_artifacts: 
          path: build/reports/detekt
          destination: detekt-reports
      - store_artifacts: 
          path: build/reports/dependency-check-report.html
          destination: security-reports

  build-and-test:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Crear local.properties
          command: echo "sdk.dir=/opt/android/sdk" > local.properties
      - fix-gradlew
      - restore-gradle-cache
      - run: ./gradlew build -x test
      - run: ./gradlew test jacocoTestReport koverXmlReport
      - save-gradle-cache
      - store_test_results: 
          path: build/test-results
      - store_artifacts: 
          path: build/reports/tests
          destination: test-reports
      - store_artifacts: 
          path: build/reports/jacoco
          destination: coverage-reports
      - persist_to_workspace:
          root: .
          paths:
            - build/reports/kover/xml/report.xml

  sonarcloud-analysis:
    executor: android-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - sonarcloud/scan:
          sonar_token_variable_name: SONAR_TOKEN

  snyk-analysis:
    executor: android-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - snyk/scan

workflows:
  library-ci:
    jobs:
      - build
      - build-and-test:
          requires:
            - build
      - sonarcloud-analysis:
          requires:
            - build-and-test
      - snyk-analysis:
          requires:
            - build-and-test
