apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name}}-postgres-pvc-v2
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
          storage: 5Gi
  storageClassName: manual


