kube-prometheus-stack:
  fullnameOverride: monitoring

  defaultRules:
    create: false

  grafana:
    admin:
      existingSecret: grafana-admin
      userKey: admin-user
      passwordKey: admin-password
    defaultDashboardsTimezone: browser
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests: { cpu: 50m, memory: 100Mi }
      limits: { memory: 200Mi }

  prometheus:
    prometheusSpec:
      scrapeInterval: 30s
      retention: 12h
      walCompression: true
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector: {}
      podMonitorNamespaceSelector: {}
      podMonitorSelector: {}
      resources:
        requests: { cpu: 100m, memory: 300Mi }
        limits: { memory: 600Mi }

  prometheusOperator:
    resources:
      requests: { cpu: 50m, memory: 100Mi }
      limits: { memory: 200Mi }

  alertmanager:
    enabled: false

  kubeEtcd:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false