{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-sm
  namespace: {{ .Values.monitoring.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.metadata.app }}
    release: monitoring-stack  
spec:
  selector:
    matchLabels:
      app: {{ .Values.metadata.app }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: {{ .Values.service.portName | default "metric" }}   # "metrics" según tu values
      path: /metrics
      interval: 15s
      scheme: http
{{- end }}

