apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  labels:
    app: {{ .Values.metadata.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.metadata.app }}
  ports:
    - name: {{ .Values.service.portName | default "http"  }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
