apiVersion: apps/v1
kind: Deployment
metadata:
  name: milibrary-api-python
  namespace: milibrary
  labels:
    app: milibrary-api-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milibrary-api-python
  template:
    metadata:
      labels:
        app: milibrary-api-python
    spec:
      containers:
      - name: api
        image: milibrary-api-python:v1.1.0
        imagePullPolicy: Never  # Importante: usar imagen local
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DB_HOST
          value: "postgres-service.milibrary.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "milibrary_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: milibrary-api-nodeport
  namespace: milibrary
  labels:
    app: milibrary-api-python
spec:
  selector:
    app: milibrary-api-python
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    protocol: TCP
    name: http
  type: NodePort
